<#
.SYNOPSIS
    minimus readme - auto readme generator
.DESCRIPTION
    generates a readme.md based on the detected project type.
.PARAMETER Help
    show this help message.
#>
param (
    [switch]$Help
)

if ($Help) {
    Write-Host "minimus readme" -ForegroundColor Cyan
    Write-Host "usage: ./readme.ps1"
    Write-Host ""
    Write-Host "scans directory and generates a basic readme.md."
    exit
}

$currentDir = Get-Location
$dirName = Split-Path $currentDir -Leaf
$readmePath = Join-Path $currentDir "README.md"

# ASCII Art
Write-Host " _ __ ___  _ _ __ (_)_ __ ___  _   _ ___ " -ForegroundColor DarkGray
Write-Host "| '_ `` _ \| | '_ \| | '_ `` _ \| | | / __|" -ForegroundColor Gray
Write-Host "| | | | | | | | | | | | | | | | |_| \__ \" -ForegroundColor White
Write-Host "|_| |_| |_|_|_| |_|_|_| |_| |_|\__,_|___/" -ForegroundColor Cyan
Write-Host "minimus readme: $currentDir" -ForegroundColor Cyan
Write-Host ""

if (Test-Path $readmePath) {
    Write-Host "  [?] README.md already exists" -ForegroundColor Yellow
    $confirm = Read-Host "  overwrite? (y/N)"
    if ($confirm -ne "y") {
        Write-Host "  [!] aborted" -ForegroundColor Yellow
        exit
    }
}

Write-Host "  [>] analyzing project..." -ForegroundColor DarkGray

$type = "generic"
$installCmd = ""
$runCmd = ""

if (Test-Path "$currentDir\package.json") {
    $type = "node.js"
    $installCmd = "npm install"
    $runCmd = "npm start"
}
elseif (Test-Path "$currentDir\requirements.txt") {
    $type = "python"
    $installCmd = "python -m venv venv; source venv/bin/activate; pip install -r requirements.txt"
    $runCmd = "python main.py"
}
elseif (Test-Path "$currentDir\pyproject.toml") {
    $type = "python (poetry)"
    $installCmd = "poetry install"
    $runCmd = "poetry run python main.py"
}
elseif (Test-Path "$currentDir\Cargo.toml") {
    $type = "rust"
    $installCmd = "cargo build"
    $runCmd = "cargo run"
}
elseif (Test-Path "$currentDir\go.mod") {
    $type = "go"
    $installCmd = "go mod tidy"
    $runCmd = "go run ."
}
elseif (Test-Path "$currentDir\Dockerfile") {
    $type = "docker"
    $installCmd = "docker build -t $dirName ."
    $runCmd = "docker run $dirName"
}

Write-Host "  [+] detected $type project" -ForegroundColor Green

$content = @"
# $dirName

> generated by minimus

## type
$type

## usage

### install
```bash
$installCmd
```

### run
```bash
$runCmd
```
"@

Set-Content -Path $readmePath -Value $content
Write-Host "  [+] generated README.md" -ForegroundColor Green
Write-Host ""
