#!/bin/bash

# minimus readme - auto readme generator

show_help() {
    echo -e "\033[1;36mminimus readme\033[0m"
    echo "usage: ./readme.sh"
    echo ""
    echo "scans directory and generates a basic readme.md."
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

# ASCII Art
echo -e "\033[1;30m _ __ ___  _ _ __ (_)_ __ ___  _   _ ___ "
echo -e "\033[0;37m| '_ \` _ \| | '_ \| | '_ \` _ \| | | / __|"
echo -e "\033[1;37m| | | | | | | | | | | | | | | | |_| \__ \\"
echo -e "\033[1;36m|_| |_| |_|_|_| |_|_|_| |_| |_|\__,_|___/\033[0m"
echo -e "\033[1;36mminimus readme: $(pwd)\033[0m"
echo ""

README_PATH="./README.md"
DIR_NAME=$(basename "$(pwd)")

if [ -f "$README_PATH" ]; then
    echo -e "  \033[1;33m[?] README.md already exists\033[0m"
    read -p "  overwrite? (y/N) " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "  \033[1;33m[!] aborted\033[0m"
        exit 0
    fi
fi

echo -e "  \033[1;30m[>] analyzing project...\033[0m"

TYPE="generic"
INSTALL_CMD=""
RUN_CMD=""

if [ -f "package.json" ]; then
    TYPE="node.js"
    INSTALL_CMD="npm install"
    RUN_CMD="npm start"
elif [ -f "requirements.txt" ]; then
    TYPE="python"
    INSTALL_CMD="python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt"
    RUN_CMD="python3 main.py"
elif [ -f "pyproject.toml" ]; then
    TYPE="python (poetry)"
    INSTALL_CMD="poetry install"
    RUN_CMD="poetry run python main.py"
elif [ -f "Cargo.toml" ]; then
    TYPE="rust"
    INSTALL_CMD="cargo build"
    RUN_CMD="cargo run"
elif [ -f "go.mod" ]; then
    TYPE="go"
    INSTALL_CMD="go mod tidy"
    RUN_CMD="go run ."
elif [ -f "Dockerfile" ]; then
    TYPE="docker"
    INSTALL_CMD="docker build -t $DIR_NAME ."
    RUN_CMD="docker run $DIR_NAME"
fi

echo -e "  \033[1;32m[+] detected $TYPE project\033[0m"

cat > "$README_PATH" <<EOF
# $DIR_NAME

> generated by minimus

## type
$TYPE

## usage

### install
\`\`\`bash
$INSTALL_CMD
\`\`\`

### run
\`\`\`bash
$RUN_CMD
\`\`\`
EOF

echo -e "  \033[1;32m[+] generated README.md\033[0m"
echo ""
